### ISSUE TITLE
Link error with arm-none-eabi-gcc 10.2.0

### ISSUE THREAD

**Issue by xmuller** [Gregwar/robotis-bootloader-maple#1]
Hi !
I tried to build this bootloader with arm-none-eabi-gcc 10.2.0 but i get the following error from ld:

*/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: section .init LMA [00000000080021a0,00000000080021ab] overlaps section .data LMA [00000000080021a0,0000000008002283]*

Do you have any idea about this ?
Also this repository is quiet old and I don't know if it's still useful. I wanted to try this one on a maple-mini, if you don't have time for this, I understand.

**Comment by Gregwar** [comment]
Hello,

Not sure why I forgot to update some files on upstream repository (git pull and it should work).

If it still doesn't work note that I use gcc 4.9, if you are on Ubuntu you can use Xenial toolchain:
https://github.com/rhoban/maple#using-xenial-toolchain-on-ubuntu-18

I also have a process to change the bootloader directly without plugging another programme, by writing a firmware that re-writes the bootloader:
https://github.com/Rhoban/Maple/tree/master/bootloader

PS: N'hésite pas à m’appeller si tu as besoin d'aide Xavier :smile:

**Comment by xmuller** [comment]
Thanks ! I will look into https://github.com/Rhoban/Maple/tree/master/bootloader.
